[versions]
alchemist = "42.3.17"

[libraries]
alchemist = { module = "it.unibo.alchemist:alchemist", version.ref = "alchemist" }
alchemist-incarnation-protelis = { module = "it.unibo.alchemist:alchemist-incarnation-protelis", version.ref = "alchemist" }
alchemist-swingui = { module = "it.unibo.alchemist:alchemist-swingui", version.ref = "alchemist" }
alchemist-physics = { module = "it.unibo.alchemist:alchemist-physics", version.ref = "alchemist" }

[bundles]
alchemist = ["alchemist", "alchemist-incarnation-protelis", "alchemist-swingui", "alchemist-physics"]

[plugins]
multiJvmTesting = "org.danilopianini.multi-jvm-test-plugin:4.3.2"
taskTree = "com.dorongold.task-tree:4.0.1"
